apiVersion: apps/v1
kind: Deployment
metadata:
  name: ndhfe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ndhfe
  template:
    metadata:
      labels:
        app: ndhfe
    spec:
      containers:
      - image: okteto.dev/ndhfe:latest
        name: ndhfe
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "ca3cd103-57c6-4b8b-86ea-ad44969aaa26"
        - name: Vless_Path
          value: "/vlfgfer5"
        - name: Vmess_UUID
          value: "ca3cd103-57c6-4b8b-86ea-ad44969aaa26"
        - name: Vmess_Path
          value: "/vmfgfgr"
        - name: Share_Path
          value: "/v2link"
